namespace ISOLib.Collections
{
    using ISOLib.Models;
    using System;
    using System.Collections.ObjectModel;
    using System.Linq;
    public class Currencies : ReadOnlyCollection<Currency>, IISO
    {
        private readonly static Currency[] _currencies = new Currency[]
        {
            new Currency(name: "United Arab Emirates dirham", alpha3: "AED", number:"784", decimals: 2),
            new Currency(name: "Afghan afghani", alpha3: "AFN", number:"971", decimals: 2),
            new Currency(name: "Albanian lek", alpha3: "ALL", number:"8", decimals: 2),
            new Currency(name: "Armenian dram", alpha3: "AMD", number:"51", decimals: 2),
            new Currency(name: "Netherlands Antillean guilder", alpha3: "ANG", number:"532", decimals: 2),
            new Currency(name: "Angolan kwanza", alpha3: "AOA", number:"973", decimals: 2),
            new Currency(name: "Argentine peso", alpha3: "ARS", number:"32", decimals: 2),
            new Currency(name: "Australian dollar", alpha3: "AUD", number:"36", decimals: 2),
            new Currency(name: "Aruban florin", alpha3: "AWG", number:"533", decimals: 2),
            new Currency(name: "Azerbaijani manat", alpha3: "AZN", number:"944", decimals: 2),
            new Currency(name: "Bosnia and Herzegovina convertible mark", alpha3: "BAM", number:"977", decimals: 2),
            new Currency(name: "Barbados dollar", alpha3: "BBD", number:"52", decimals: 2),
            new Currency(name: "Bangladeshi taka", alpha3: "BDT", number:"50", decimals: 2),
            new Currency(name: "Bulgarian lev", alpha3: "BGN", number:"975", decimals: 2),
            new Currency(name: "Bahraini dinar", alpha3: "BHD", number:"48", decimals: 3),
            new Currency(name: "Burundian franc", alpha3: "BIF", number:"108", decimals: 0),
            new Currency(name: "Bermudian dollar (customarily known as Bermuda dollar)", alpha3: "BMD", number:"60", decimals: 2),
            new Currency(name: "Brunei dollar", alpha3: "BND", number:"96", decimals: 2),
            new Currency(name: "Boliviano", alpha3: "BOB", number:"68", decimals: 2),
            new Currency(name: "Bolivian Mvdol (funds code)", alpha3: "BOV", number:"984", decimals: 2),
            new Currency(name: "Brazilian real", alpha3: "BRL", number:"986", decimals: 2),
            new Currency(name: "Bahamian dollar", alpha3: "BSD", number:"44", decimals: 2),
            new Currency(name: "Bhutanese ngultrum", alpha3: "BTN", number:"64", decimals: 2),
            new Currency(name: "Botswana pula", alpha3: "BWP", number:"72", decimals: 2),
            new Currency(name: "Belarusian ruble", alpha3: "BYR", number:"974", decimals: 0),
            new Currency(name: "Belize dollar", alpha3: "BZD", number:"84", decimals: 2),
            new Currency(name: "Canadian dollar", alpha3: "CAD", number:"124", decimals: 2),
            new Currency(name: "Congolese franc", alpha3: "CDF", number:"976", decimals: 2),
            new Currency(name: "WIR Euro (complementary currency)", alpha3: "CHE", number:"947", decimals: 2),
            new Currency(name: "Swiss franc", alpha3: "CHF", number:"756", decimals: 2),
            new Currency(name: "WIR Franc (complementary currency)", alpha3: "CHW", number:"948", decimals: 2),
            new Currency(name: "Unidad de Fomento (funds code)", alpha3: "CLF", number:"990", decimals: 0),
            new Currency(name: "Chilean peso", alpha3: "CLP", number:"152", decimals: 0),
            new Currency(name: "Chinese yuan", alpha3: "CNY", number:"156", decimals: 2),
            new Currency(name: "Colombian peso", alpha3: "COP", number:"170", decimals: 2),
            new Currency(name: "Unidad de Valor Real", alpha3: "COU", number:"970", decimals: 2),
            new Currency(name: "Costa Rican colon", alpha3: "CRC", number:"188", decimals: 2),
            new Currency(name: "Cuban convertible peso", alpha3: "CUC", number:"931", decimals: 2),
            new Currency(name: "Cuban peso", alpha3: "CUP", number:"192", decimals: 2),
            new Currency(name: "Cape Verde escudo", alpha3: "CVE", number:"132", decimals: 0),
            new Currency(name: "Czech koruna", alpha3: "CZK", number:"203", decimals: 2),
            new Currency(name: "Djiboutian franc", alpha3: "DJF", number:"262", decimals: 0),
            new Currency(name: "Danish krone", alpha3: "DKK", number:"208", decimals: 2),
            new Currency(name: "Dominican peso", alpha3: "DOP", number:"214", decimals: 2),
            new Currency(name: "Algerian dinar", alpha3: "DZD", number:"12", decimals: 2),
            new Currency(name: "Egyptian pound", alpha3: "EGP", number:"818", decimals: 2),
            new Currency(name: "Eritrean nakfa", alpha3: "ERN", number:"232", decimals: 2),
            new Currency(name: "Ethiopian birr", alpha3: "ETB", number:"230", decimals: 2),
            new Currency(name: "Euro", alpha3: "EUR", number:"978", decimals: 2),
            new Currency(name: "Fiji dollar", alpha3: "FJD", number:"242", decimals: 2),
            new Currency(name: "Falkland Islands pound", alpha3: "FKP", number:"238", decimals: 2),
            new Currency(name: "Pound sterling", alpha3: "GBP", number:"826", decimals: 2),
            new Currency(name: "Georgian lari", alpha3: "GEL", number:"981", decimals: 2),
            new Currency(name: "Ghanaian cedi", alpha3: "GHS", number:"936", decimals: 2),
            new Currency(name: "Gibraltar pound", alpha3: "GIP", number:"292", decimals: 2),
            new Currency(name: "Gambian dalasi", alpha3: "GMD", number:"270", decimals: 2),
            new Currency(name: "Guinean franc", alpha3: "GNF", number:"324", decimals: 0),
            new Currency(name: "Guatemalan quetzal", alpha3: "GTQ", number:"320", decimals: 2),
            new Currency(name: "Guyanese dollar", alpha3: "GYD", number:"328", decimals: 2),
            new Currency(name: "Hong Kong dollar", alpha3: "HKD", number:"344", decimals: 2),
            new Currency(name: "Honduran lempira", alpha3: "HNL", number:"340", decimals: 2),
            new Currency(name: "Croatian kuna", alpha3: "HRK", number:"191", decimals: 2),
            new Currency(name: "Haitian gourde", alpha3: "HTG", number:"332", decimals: 2),
            new Currency(name: "Hungarian forint", alpha3: "HUF", number:"348", decimals: 2),
            new Currency(name: "Indonesian rupiah", alpha3: "IDR", number:"360", decimals: 2),
            new Currency(name: "Israeli new shekel", alpha3: "ILS", number:"376", decimals: 2),
            new Currency(name: "Indian rupee", alpha3: "INR", number:"356", decimals: 2),
            new Currency(name: "Iraqi dinar", alpha3: "IQD", number:"368", decimals: 3),
            new Currency(name: "Iranian rial", alpha3: "IRR", number:"364", decimals: 0),
            new Currency(name: "Icelandic króna", alpha3: "ISK", number:"352", decimals: 0),
            new Currency(name: "Jamaican dollar", alpha3: "JMD", number:"388", decimals: 2),
            new Currency(name: "Jordanian dinar", alpha3: "JOD", number:"400", decimals: 3),
            new Currency(name: "Japanese yen", alpha3: "JPY", number:"392", decimals: 0),
            new Currency(name: "Kenyan shilling", alpha3: "KES", number:"404", decimals: 2),
            new Currency(name: "Kyrgyzstani som", alpha3: "KGS", number:"417", decimals: 2),
            new Currency(name: "Cambodian riel", alpha3: "KHR", number:"116", decimals: 2),
            new Currency(name: "Comoro franc", alpha3: "KMF", number:"174", decimals: 0),
            new Currency(name: "North Korean won", alpha3: "KPW", number:"408", decimals: 0),
            new Currency(name: "South Korean won", alpha3: "KRW", number:"410", decimals: 0),
            new Currency(name: "Kuwaiti dinar", alpha3: "KWD", number:"414", decimals: 3),
            new Currency(name: "Cayman Islands dollar", alpha3: "KYD", number:"136", decimals: 2),
            new Currency(name: "Kazakhstani tenge", alpha3: "KZT", number:"398", decimals: 2),
            new Currency(name: "Lao kip", alpha3: "LAK", number:"418", decimals: 0),
            new Currency(name: "Lebanese pound", alpha3: "LBP", number:"422", decimals: 0),
            new Currency(name: "Sri Lankan rupee", alpha3: "LKR", number:"144", decimals: 2),
            new Currency(name: "Liberian dollar", alpha3: "LRD", number:"430", decimals: 2),
            new Currency(name: "Lesotho loti", alpha3: "LSL", number:"426", decimals: 2),
            new Currency(name: "Lithuanian litas", alpha3: "LTL", number:"440", decimals: 2),
            new Currency(name: "Latvian lats", alpha3: "LVL", number:"428", decimals: 2),
            new Currency(name: "Libyan dinar", alpha3: "LYD", number:"434", decimals: 3),
            new Currency(name: "Moroccan dirham", alpha3: "MAD", number:"504", decimals: 2),
            new Currency(name: "Moldovan leu", alpha3: "MDL", number:"498", decimals: 2),
            new Currency(name: "Malagasy ariary", alpha3: "MGA", number:"969", decimals: 0),
            new Currency(name: "Macedonian denar", alpha3: "MKD", number:"807", decimals: 0),
            new Currency(name: "Myanma kyat", alpha3: "MMK", number:"104", decimals: 0),
            new Currency(name: "Mongolian tugrik", alpha3: "MNT", number:"496", decimals: 2),
            new Currency(name: "Macanese pataca", alpha3: "MOP", number:"446", decimals: 2),
            new Currency(name: "Mauritanian ouguiya", alpha3: "MRO", number:"478", decimals: 0),
            new Currency(name: "Mauritian rupee", alpha3: "MUR", number:"480", decimals: 2),
            new Currency(name: "Maldivian rufiyaa", alpha3: "MVR", number:"462", decimals: 2),
            new Currency(name: "Malawian kwacha", alpha3: "MWK", number:"454", decimals: 2),
            new Currency(name: "Mexican peso", alpha3: "MXN", number:"484", decimals: 2),
            new Currency(name: "Mexican Unidad de Inversion (UDI) (funds code)", alpha3: "MXV", number:"979", decimals: 2),
            new Currency(name: "Malaysian ringgit", alpha3: "MYR", number:"458", decimals: 2),
            new Currency(name: "Mozambican metical", alpha3: "MZN", number:"943", decimals: 2),
            new Currency(name: "Namibian dollar", alpha3: "NAD", number:"516", decimals: 2),
            new Currency(name: "Nigerian naira", alpha3: "NGN", number:"566", decimals: 2),
            new Currency(name: "Nicaraguan córdoba", alpha3: "NIO", number:"558", decimals: 2),
            new Currency(name: "Norwegian krone", alpha3: "NOK", number:"578", decimals: 2),
            new Currency(name: "Nepalese rupee", alpha3: "NPR", number:"524", decimals: 2),
            new Currency(name: "New Zealand dollar", alpha3: "NZD", number:"554", decimals: 2),
            new Currency(name: "Omani rial", alpha3: "OMR", number:"512", decimals: 3),
            new Currency(name: "Panamanian balboa", alpha3: "PAB", number:"590", decimals: 2),
            new Currency(name: "Peruvian nuevo sol", alpha3: "PEN", number:"604", decimals: 2),
            new Currency(name: "Papua New Guinean kina", alpha3: "PGK", number:"598", decimals: 2),
            new Currency(name: "Philippine peso", alpha3: "PHP", number:"608", decimals: 2),
            new Currency(name: "Pakistani rupee", alpha3: "PKR", number:"586", decimals: 2),
            new Currency(name: "Polish złoty", alpha3: "PLN", number:"985", decimals: 2),
            new Currency(name: "Paraguayan guaraní", alpha3: "PYG", number:"600", decimals: 0),
            new Currency(name: "Qatari riyal", alpha3: "QAR", number:"634", decimals: 2),
            new Currency(name: "Romanian new leu", alpha3: "RON", number:"946", decimals: 2),
            new Currency(name: "Serbian dinar", alpha3: "RSD", number:"941", decimals: 2),
            new Currency(name: "Russian rouble", alpha3: "RUB", number:"643", decimals: 2),
            new Currency(name: "Rwandan franc", alpha3: "RWF", number:"646", decimals: 0),
            new Currency(name: "Saudi riyal", alpha3: "SAR", number:"682", decimals: 2),
            new Currency(name: "Solomon Islands dollar", alpha3: "SBD", number:"90", decimals: 2),
            new Currency(name: "Seychelles rupee", alpha3: "SCR", number:"690", decimals: 2),
            new Currency(name: "Sudanese pound", alpha3: "SDG", number:"938", decimals: 2),
            new Currency(name: "Swedish krona/kronor", alpha3: "SEK", number:"752", decimals: 2),
            new Currency(name: "Singapore dollar", alpha3: "SGD", number:"702", decimals: 2),
            new Currency(name: "Saint Helena pound", alpha3: "SHP", number:"654", decimals: 2),
            new Currency(name: "Sierra Leonean leone", alpha3: "SLL", number:"694", decimals: 0),
            new Currency(name: "Somali shilling", alpha3: "SOS", number:"706", decimals: 2),
            new Currency(name: "Surinamese dollar", alpha3: "SRD", number:"968", decimals: 2),
            new Currency(name: "South Sudanese pound", alpha3: "SSP", number:"728", decimals: 2),
            new Currency(name: "São Tomé and Príncipe dobra", alpha3: "STD", number:"678", decimals: 0),
            new Currency(name: "Syrian pound", alpha3: "SYP", number:"760", decimals: 2),
            new Currency(name: "Swazi lilangeni", alpha3: "SZL", number:"748", decimals: 2),
            new Currency(name: "Thai baht", alpha3: "THB", number:"764", decimals: 2),
            new Currency(name: "Tajikistani somoni", alpha3: "TJS", number:"972", decimals: 2),
            new Currency(name: "Turkmenistani manat", alpha3: "TMT", number:"934", decimals: 2),
            new Currency(name: "Tunisian dinar", alpha3: "TND", number:"788", decimals: 3),
            new Currency(name: "Tongan paʻanga", alpha3: "TOP", number:"776", decimals: 2),
            new Currency(name: "Turkish lira", alpha3: "TRY", number:"949", decimals: 2),
            new Currency(name: "Trinidad and Tobago dollar", alpha3: "TTD", number:"780", decimals: 2),
            new Currency(name: "New Taiwan dollar", alpha3: "TWD", number:"901", decimals: 2),
            new Currency(name: "Tanzanian shilling", alpha3: "TZS", number:"834", decimals: 2),
            new Currency(name: "Ukrainian hryvnia", alpha3: "UAH", number:"980", decimals: 2),
            new Currency(name: "Ugandan shilling", alpha3: "UGX", number:"800", decimals: 2),
            new Currency(name: "United States dollar", alpha3: "USD", number:"840", decimals: 2),
            new Currency(name: "United States dollar (next day) (funds code)", alpha3: "USN", number:"997", decimals: 2),
            new Currency(name: "United States dollar (same day) (funds code)", alpha3: "USS", number:"998", decimals: 2),
            new Currency(name: "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)", alpha3: "UYI", number:"940", decimals: 0),
            new Currency(name: "Uruguayan peso", alpha3: "UYU", number:"858", decimals: 2),
            new Currency(name: "Uzbekistan som", alpha3: "UZS", number:"860", decimals: 2),
            new Currency(name: "Venezuelan bolívar fuerte", alpha3: "VEF", number:"937", decimals: 2),
            new Currency(name: "Vietnamese dong", alpha3: "VND", number:"704", decimals: 0),
            new Currency(name: "Vanuatu vatu", alpha3: "VUV", number:"548", decimals: 0),
            new Currency(name: "Samoan tala", alpha3: "WST", number:"882", decimals: 2),
            new Currency(name: "CFA franc BEAC", alpha3: "XAF", number:"950", decimals: 0),
            new Currency(name: "Silver (one troy ounce)", alpha3: "XAG", number:"961", decimals: null),
            new Currency(name: "Gold (one troy ounce)", alpha3: "XAU", number:"959", decimals: null),
            new Currency(name: "European Composite Unit (EURCO) (bond market unit)", alpha3: "XBA", number:"955", decimals: null),
            new Currency(name: "European Monetary Unit (E.M.U.-6) (bond market unit)", alpha3: "XBB", number:"956", decimals: null),
            new Currency(name: "European Unit of Account 9 (E.U.A.-9) (bond market unit)", alpha3: "XBC", number:"957", decimals: null),
            new Currency(name: "European Unit of Account 17 (E.U.A.-17) (bond market unit)", alpha3: "XBD", number:"958", decimals: null),
            new Currency(name: "East Caribbean dollar", alpha3: "XCD", number:"951", decimals: 2),
            new Currency(name: "Special drawing rights", alpha3: "XDR", number:"960", decimals: null),
            new Currency(name: "UIC franc (special settlement currency)", alpha3: "XFU", number:"null", decimals: null),
            new Currency(name: "CFA franc BCEAO", alpha3: "XOF", number:"952", decimals: 0),
            new Currency(name: "Palladium (one troy ounce)", alpha3: "XPD", number:"964", decimals: null),
            new Currency(name: "CFP franc", alpha3: "XPF", number:"953", decimals: 0),
            new Currency(name: "Platinum (one troy ounce)", alpha3: "XPT", number:"962", decimals: null),
            new Currency(name: "Code reserved for testing purposes", alpha3: "XTS", number:"963", decimals: null),
            new Currency(name: "No currency", alpha3: "XXX", number:"999", decimals: null),
            new Currency(name: "Yemeni rial", alpha3: "YER", number:"886", decimals: 2),
            new Currency(name: "South African rand", alpha3: "ZAR", number:"710", decimals: 2),
            new Currency(name: "Zambian kwacha", alpha3: "ZMW", number:"967", decimals: 2),
        };

        internal Currencies() : base(_currencies) { }

        public int Number { get; } = 4217;
        public string Name { get; } = "ISO 4217";
        public string Wiki { get; } = "https://en.wikipedia.org/wiki/ISO_4217";

        /// <summary>
        /// Gets the <see cref="Currency"/> object corresponding to the specified currency name or Alpha-3 code.
        /// </summary>
        /// <param name="currencyName">The currency name or Alpha-3 code to retrieve.</param>
        /// <returns>The <see cref="Currency"/> object representing the specified currency.</returns>
        /// <exception cref="ArgumentException">Thrown when the specified currency name or Alpha-3 code does not match any currency in the collection.</exception>
        public Currency this[string currencyName]
        {
            get
            {
                var currency = Items.FirstOrDefault(c => c.Name == currencyName || c.Alpha3 == currencyName);
                if (currency == null)
                {
                    throw new ArgumentException("Currency not found", nameof(currencyName));
                }
                return currency;
            }
        }
    }
}
