namespace ISOLib.Collections
{
    using ISOLib.Models;
    using System;
    using System.Collections.ObjectModel;
    using System.Linq;
    public class Currencies : ReadOnlyCollection<Currency>, IISO
    {
        private readonly static Currency[] _currencies = new Currency[]
        {
            new Currency(name: "United Arab Emirates dirham", alpha3: "AED", number:"784", minorUnit: 2),
            new Currency(name: "Afghan afghani", alpha3: "AFN", number:"971", minorUnit: 2),
            new Currency(name: "Albanian lek", alpha3: "ALL", number:"8", minorUnit: 2),
            new Currency(name: "Armenian dram", alpha3: "AMD", number:"51", minorUnit: 2),
            new Currency(name: "Netherlands Antillean guilder", alpha3: "ANG", number:"532", minorUnit: 2),
            new Currency(name: "Angolan kwanza", alpha3: "AOA", number:"973", minorUnit: 2),
            new Currency(name: "Argentine peso", alpha3: "ARS", number:"32", minorUnit: 2),
            new Currency(name: "Australian dollar", alpha3: "AUD", number:"36", minorUnit: 2),
            new Currency(name: "Aruban florin", alpha3: "AWG", number:"533", minorUnit: 2),
            new Currency(name: "Azerbaijani manat", alpha3: "AZN", number:"944", minorUnit: 2),
            new Currency(name: "Bosnia and Herzegovina convertible mark", alpha3: "BAM", number:"977", minorUnit: 2),
            new Currency(name: "Barbados dollar", alpha3: "BBD", number:"52", minorUnit: 2),
            new Currency(name: "Bangladeshi taka", alpha3: "BDT", number:"50", minorUnit: 2),
            new Currency(name: "Bulgarian lev", alpha3: "BGN", number:"975", minorUnit: 2),
            new Currency(name: "Bahraini dinar", alpha3: "BHD", number:"48", minorUnit: 3),
            new Currency(name: "Burundian franc", alpha3: "BIF", number:"108", minorUnit: 0),
            new Currency(name: "Bermudian dollar (customarily known as Bermuda dollar)", alpha3: "BMD", number:"60", minorUnit: 2),
            new Currency(name: "Brunei dollar", alpha3: "BND", number:"96", minorUnit: 2),
            new Currency(name: "Boliviano", alpha3: "BOB", number:"68", minorUnit: 2),
            new Currency(name: "Bolivian Mvdol (funds code)", alpha3: "BOV", number:"984", minorUnit: 2),
            new Currency(name: "Brazilian real", alpha3: "BRL", number:"986", minorUnit: 2),
            new Currency(name: "Bahamian dollar", alpha3: "BSD", number:"44", minorUnit: 2),
            new Currency(name: "Bhutanese ngultrum", alpha3: "BTN", number:"64", minorUnit: 2),
            new Currency(name: "Botswana pula", alpha3: "BWP", number:"72", minorUnit: 2),
            new Currency(name: "Belarusian ruble", alpha3: "BYR", number:"974", minorUnit: 0),
            new Currency(name: "Belize dollar", alpha3: "BZD", number:"84", minorUnit: 2),
            new Currency(name: "Canadian dollar", alpha3: "CAD", number:"124", minorUnit: 2),
            new Currency(name: "Congolese franc", alpha3: "CDF", number:"976", minorUnit: 2),
            new Currency(name: "WIR Euro (complementary currency)", alpha3: "CHE", number:"947", minorUnit: 2),
            new Currency(name: "Swiss franc", alpha3: "CHF", number:"756", minorUnit: 2),
            new Currency(name: "WIR Franc (complementary currency)", alpha3: "CHW", number:"948", minorUnit: 2),
            new Currency(name: "Unidad de Fomento (funds code)", alpha3: "CLF", number:"990", minorUnit: 0),
            new Currency(name: "Chilean peso", alpha3: "CLP", number:"152", minorUnit: 0),
            new Currency(name: "Chinese yuan", alpha3: "CNY", number:"156", minorUnit: 2),
            new Currency(name: "Colombian peso", alpha3: "COP", number:"170", minorUnit: 2),
            new Currency(name: "Unidad de Valor Real", alpha3: "COU", number:"970", minorUnit: 2),
            new Currency(name: "Costa Rican colon", alpha3: "CRC", number:"188", minorUnit: 2),
            new Currency(name: "Cuban convertible peso", alpha3: "CUC", number:"931", minorUnit: 2),
            new Currency(name: "Cuban peso", alpha3: "CUP", number:"192", minorUnit: 2),
            new Currency(name: "Cape Verde escudo", alpha3: "CVE", number:"132", minorUnit: 0),
            new Currency(name: "Czech koruna", alpha3: "CZK", number:"203", minorUnit: 2),
            new Currency(name: "Djiboutian franc", alpha3: "DJF", number:"262", minorUnit: 0),
            new Currency(name: "Danish krone", alpha3: "DKK", number:"208", minorUnit: 2),
            new Currency(name: "Dominican peso", alpha3: "DOP", number:"214", minorUnit: 2),
            new Currency(name: "Algerian dinar", alpha3: "DZD", number:"12", minorUnit: 2),
            new Currency(name: "Egyptian pound", alpha3: "EGP", number:"818", minorUnit: 2),
            new Currency(name: "Eritrean nakfa", alpha3: "ERN", number:"232", minorUnit: 2),
            new Currency(name: "Ethiopian birr", alpha3: "ETB", number:"230", minorUnit: 2),
            new Currency(name: "Euro", alpha3: "EUR", number:"978", minorUnit: 2),
            new Currency(name: "Fiji dollar", alpha3: "FJD", number:"242", minorUnit: 2),
            new Currency(name: "Falkland Islands pound", alpha3: "FKP", number:"238", minorUnit: 2),
            new Currency(name: "Pound sterling", alpha3: "GBP", number:"826", minorUnit: 2),
            new Currency(name: "Georgian lari", alpha3: "GEL", number:"981", minorUnit: 2),
            new Currency(name: "Ghanaian cedi", alpha3: "GHS", number:"936", minorUnit: 2),
            new Currency(name: "Gibraltar pound", alpha3: "GIP", number:"292", minorUnit: 2),
            new Currency(name: "Gambian dalasi", alpha3: "GMD", number:"270", minorUnit: 2),
            new Currency(name: "Guinean franc", alpha3: "GNF", number:"324", minorUnit: 0),
            new Currency(name: "Guatemalan quetzal", alpha3: "GTQ", number:"320", minorUnit: 2),
            new Currency(name: "Guyanese dollar", alpha3: "GYD", number:"328", minorUnit: 2),
            new Currency(name: "Hong Kong dollar", alpha3: "HKD", number:"344", minorUnit: 2),
            new Currency(name: "Honduran lempira", alpha3: "HNL", number:"340", minorUnit: 2),
            new Currency(name: "Croatian kuna", alpha3: "HRK", number:"191", minorUnit: 2),
            new Currency(name: "Haitian gourde", alpha3: "HTG", number:"332", minorUnit: 2),
            new Currency(name: "Hungarian forint", alpha3: "HUF", number:"348", minorUnit: 2),
            new Currency(name: "Indonesian rupiah", alpha3: "IDR", number:"360", minorUnit: 2),
            new Currency(name: "Israeli new shekel", alpha3: "ILS", number:"376", minorUnit: 2),
            new Currency(name: "Indian rupee", alpha3: "INR", number:"356", minorUnit: 2),
            new Currency(name: "Iraqi dinar", alpha3: "IQD", number:"368", minorUnit: 3),
            new Currency(name: "Iranian rial", alpha3: "IRR", number:"364", minorUnit: 0),
            new Currency(name: "Icelandic króna", alpha3: "ISK", number:"352", minorUnit: 0),
            new Currency(name: "Jamaican dollar", alpha3: "JMD", number:"388", minorUnit: 2),
            new Currency(name: "Jordanian dinar", alpha3: "JOD", number:"400", minorUnit: 3),
            new Currency(name: "Japanese yen", alpha3: "JPY", number:"392", minorUnit: 0),
            new Currency(name: "Kenyan shilling", alpha3: "KES", number:"404", minorUnit: 2),
            new Currency(name: "Kyrgyzstani som", alpha3: "KGS", number:"417", minorUnit: 2),
            new Currency(name: "Cambodian riel", alpha3: "KHR", number:"116", minorUnit: 2),
            new Currency(name: "Comoro franc", alpha3: "KMF", number:"174", minorUnit: 0),
            new Currency(name: "North Korean won", alpha3: "KPW", number:"408", minorUnit: 0),
            new Currency(name: "South Korean won", alpha3: "KRW", number:"410", minorUnit: 0),
            new Currency(name: "Kuwaiti dinar", alpha3: "KWD", number:"414", minorUnit: 3),
            new Currency(name: "Cayman Islands dollar", alpha3: "KYD", number:"136", minorUnit: 2),
            new Currency(name: "Kazakhstani tenge", alpha3: "KZT", number:"398", minorUnit: 2),
            new Currency(name: "Lao kip", alpha3: "LAK", number:"418", minorUnit: 0),
            new Currency(name: "Lebanese pound", alpha3: "LBP", number:"422", minorUnit: 0),
            new Currency(name: "Sri Lankan rupee", alpha3: "LKR", number:"144", minorUnit: 2),
            new Currency(name: "Liberian dollar", alpha3: "LRD", number:"430", minorUnit: 2),
            new Currency(name: "Lesotho loti", alpha3: "LSL", number:"426", minorUnit: 2),
            new Currency(name: "Lithuanian litas", alpha3: "LTL", number:"440", minorUnit: 2),
            new Currency(name: "Latvian lats", alpha3: "LVL", number:"428", minorUnit: 2),
            new Currency(name: "Libyan dinar", alpha3: "LYD", number:"434", minorUnit: 3),
            new Currency(name: "Moroccan dirham", alpha3: "MAD", number:"504", minorUnit: 2),
            new Currency(name: "Moldovan leu", alpha3: "MDL", number:"498", minorUnit: 2),
            new Currency(name: "Malagasy ariary", alpha3: "MGA", number:"969", minorUnit: 0),
            new Currency(name: "Macedonian denar", alpha3: "MKD", number:"807", minorUnit: 0),
            new Currency(name: "Myanma kyat", alpha3: "MMK", number:"104", minorUnit: 0),
            new Currency(name: "Mongolian tugrik", alpha3: "MNT", number:"496", minorUnit: 2),
            new Currency(name: "Macanese pataca", alpha3: "MOP", number:"446", minorUnit: 2),
            new Currency(name: "Mauritanian ouguiya", alpha3: "MRO", number:"478", minorUnit: 0),
            new Currency(name: "Mauritian rupee", alpha3: "MUR", number:"480", minorUnit: 2),
            new Currency(name: "Maldivian rufiyaa", alpha3: "MVR", number:"462", minorUnit: 2),
            new Currency(name: "Malawian kwacha", alpha3: "MWK", number:"454", minorUnit: 2),
            new Currency(name: "Mexican peso", alpha3: "MXN", number:"484", minorUnit: 2),
            new Currency(name: "Mexican Unidad de Inversion (UDI) (funds code)", alpha3: "MXV", number:"979", minorUnit: 2),
            new Currency(name: "Malaysian ringgit", alpha3: "MYR", number:"458", minorUnit: 2),
            new Currency(name: "Mozambican metical", alpha3: "MZN", number:"943", minorUnit: 2),
            new Currency(name: "Namibian dollar", alpha3: "NAD", number:"516", minorUnit: 2),
            new Currency(name: "Nigerian naira", alpha3: "NGN", number:"566", minorUnit: 2),
            new Currency(name: "Nicaraguan córdoba", alpha3: "NIO", number:"558", minorUnit: 2),
            new Currency(name: "Norwegian krone", alpha3: "NOK", number:"578", minorUnit: 2),
            new Currency(name: "Nepalese rupee", alpha3: "NPR", number:"524", minorUnit: 2),
            new Currency(name: "New Zealand dollar", alpha3: "NZD", number:"554", minorUnit: 2),
            new Currency(name: "Omani rial", alpha3: "OMR", number:"512", minorUnit: 3),
            new Currency(name: "Panamanian balboa", alpha3: "PAB", number:"590", minorUnit: 2),
            new Currency(name: "Peruvian nuevo sol", alpha3: "PEN", number:"604", minorUnit: 2),
            new Currency(name: "Papua New Guinean kina", alpha3: "PGK", number:"598", minorUnit: 2),
            new Currency(name: "Philippine peso", alpha3: "PHP", number:"608", minorUnit: 2),
            new Currency(name: "Pakistani rupee", alpha3: "PKR", number:"586", minorUnit: 2),
            new Currency(name: "Polish złoty", alpha3: "PLN", number:"985", minorUnit: 2),
            new Currency(name: "Paraguayan guaraní", alpha3: "PYG", number:"600", minorUnit: 0),
            new Currency(name: "Qatari riyal", alpha3: "QAR", number:"634", minorUnit: 2),
            new Currency(name: "Romanian new leu", alpha3: "RON", number:"946", minorUnit: 2),
            new Currency(name: "Serbian dinar", alpha3: "RSD", number:"941", minorUnit: 2),
            new Currency(name: "Russian rouble", alpha3: "RUB", number:"643", minorUnit: 2),
            new Currency(name: "Rwandan franc", alpha3: "RWF", number:"646", minorUnit: 0),
            new Currency(name: "Saudi riyal", alpha3: "SAR", number:"682", minorUnit: 2),
            new Currency(name: "Solomon Islands dollar", alpha3: "SBD", number:"90", minorUnit: 2),
            new Currency(name: "Seychelles rupee", alpha3: "SCR", number:"690", minorUnit: 2),
            new Currency(name: "Sudanese pound", alpha3: "SDG", number:"938", minorUnit: 2),
            new Currency(name: "Swedish krona/kronor", alpha3: "SEK", number:"752", minorUnit: 2),
            new Currency(name: "Singapore dollar", alpha3: "SGD", number:"702", minorUnit: 2),
            new Currency(name: "Saint Helena pound", alpha3: "SHP", number:"654", minorUnit: 2),
            new Currency(name: "Sierra Leonean leone", alpha3: "SLL", number:"694", minorUnit: 0),
            new Currency(name: "Somali shilling", alpha3: "SOS", number:"706", minorUnit: 2),
            new Currency(name: "Surinamese dollar", alpha3: "SRD", number:"968", minorUnit: 2),
            new Currency(name: "South Sudanese pound", alpha3: "SSP", number:"728", minorUnit: 2),
            new Currency(name: "São Tomé and Príncipe dobra", alpha3: "STD", number:"678", minorUnit: 0),
            new Currency(name: "Syrian pound", alpha3: "SYP", number:"760", minorUnit: 2),
            new Currency(name: "Swazi lilangeni", alpha3: "SZL", number:"748", minorUnit: 2),
            new Currency(name: "Thai baht", alpha3: "THB", number:"764", minorUnit: 2),
            new Currency(name: "Tajikistani somoni", alpha3: "TJS", number:"972", minorUnit: 2),
            new Currency(name: "Turkmenistani manat", alpha3: "TMT", number:"934", minorUnit: 2),
            new Currency(name: "Tunisian dinar", alpha3: "TND", number:"788", minorUnit: 3),
            new Currency(name: "Tongan paʻanga", alpha3: "TOP", number:"776", minorUnit: 2),
            new Currency(name: "Turkish lira", alpha3: "TRY", number:"949", minorUnit: 2),
            new Currency(name: "Trinidad and Tobago dollar", alpha3: "TTD", number:"780", minorUnit: 2),
            new Currency(name: "New Taiwan dollar", alpha3: "TWD", number:"901", minorUnit: 2),
            new Currency(name: "Tanzanian shilling", alpha3: "TZS", number:"834", minorUnit: 2),
            new Currency(name: "Ukrainian hryvnia", alpha3: "UAH", number:"980", minorUnit: 2),
            new Currency(name: "Ugandan shilling", alpha3: "UGX", number:"800", minorUnit: 2),
            new Currency(name: "United States dollar", alpha3: "USD", number:"840", minorUnit: 2),
            new Currency(name: "United States dollar (next day) (funds code)", alpha3: "USN", number:"997", minorUnit: 2),
            new Currency(name: "United States dollar (same day) (funds code)", alpha3: "USS", number:"998", minorUnit: 2),
            new Currency(name: "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)", alpha3: "UYI", number:"940", minorUnit: 0),
            new Currency(name: "Uruguayan peso", alpha3: "UYU", number:"858", minorUnit: 2),
            new Currency(name: "Uzbekistan som", alpha3: "UZS", number:"860", minorUnit: 2),
            new Currency(name: "Venezuelan bolívar fuerte", alpha3: "VEF", number:"937", minorUnit: 2),
            new Currency(name: "Vietnamese dong", alpha3: "VND", number:"704", minorUnit: 0),
            new Currency(name: "Vanuatu vatu", alpha3: "VUV", number:"548", minorUnit: 0),
            new Currency(name: "Samoan tala", alpha3: "WST", number:"882", minorUnit: 2),
            new Currency(name: "CFA franc BEAC", alpha3: "XAF", number:"950", minorUnit: 0),
            new Currency(name: "Silver (one troy ounce)", alpha3: "XAG", number:"961", minorUnit: null),
            new Currency(name: "Gold (one troy ounce)", alpha3: "XAU", number:"959", minorUnit: null),
            new Currency(name: "European Composite Unit (EURCO) (bond market unit)", alpha3: "XBA", number:"955", minorUnit: null),
            new Currency(name: "European Monetary Unit (E.M.U.-6) (bond market unit)", alpha3: "XBB", number:"956", minorUnit: null),
            new Currency(name: "European Unit of Account 9 (E.U.A.-9) (bond market unit)", alpha3: "XBC", number:"957", minorUnit: null),
            new Currency(name: "European Unit of Account 17 (E.U.A.-17) (bond market unit)", alpha3: "XBD", number:"958", minorUnit: null),
            new Currency(name: "East Caribbean dollar", alpha3: "XCD", number:"951", minorUnit: 2),
            new Currency(name: "Special drawing rights", alpha3: "XDR", number:"960", minorUnit: null),
            new Currency(name: "UIC franc (special settlement currency)", alpha3: "XFU", number:"null", minorUnit: null),
            new Currency(name: "CFA franc BCEAO", alpha3: "XOF", number:"952", minorUnit: 0),
            new Currency(name: "Palladium (one troy ounce)", alpha3: "XPD", number:"964", minorUnit: null),
            new Currency(name: "CFP franc", alpha3: "XPF", number:"953", minorUnit: 0),
            new Currency(name: "Platinum (one troy ounce)", alpha3: "XPT", number:"962", minorUnit: null),
            new Currency(name: "Code reserved for testing purposes", alpha3: "XTS", number:"963", minorUnit: null),
            new Currency(name: "No currency", alpha3: "XXX", number:"999", minorUnit: null),
            new Currency(name: "Yemeni rial", alpha3: "YER", number:"886", minorUnit: 2),
            new Currency(name: "South African rand", alpha3: "ZAR", number:"710", minorUnit: 2),
            new Currency(name: "Zambian kwacha", alpha3: "ZMW", number:"967", minorUnit: 2),
        };

        internal Currencies() : base(_currencies) { }

        public int Number { get; } = 4217;
        public string Name { get; } = "ISO 4217";
        public string Wiki { get; } = "https://en.wikipedia.org/wiki/ISO_4217";

        /// <summary>
        /// Gets the <see cref="Currency"/> object corresponding to the specified currency name or Alpha-3 code.
        /// </summary>
        /// <param name="currencyName">The currency name or Alpha-3 code to retrieve.</param>
        /// <returns>The <see cref="Currency"/> object representing the specified currency.</returns>
        /// <exception cref="ArgumentException">Thrown when the specified currency name or Alpha-3 code does not match any currency in the collection.</exception>
        public Currency this[string currencyName]
        {
            get
            {
                var currencyId = currencyName.ToLower();
                var currency = Items.FirstOrDefault(c => c.Name.ToLower() == currencyId || c.Alpha3.ToLower() == currencyId);
                return currency ?? throw new ArgumentException("Currency not found", nameof(currencyName));
            }
        }
    }
}
